apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q7tw495aq-python 
  janus-idp.io/tekton: q7tw495aq-python
  backstage.io/kubernetes-id: q7tw495aq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q7tw495aq-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml